[workspace]
authors = ["Sangeetha Nandakumar <98574336+sangeethankumar@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "German-Study-Buddy"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
hugo = ">=0.151.0,<0.152"
